import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="header">

        <div className="logo">
        <img src="/imagens/tier11.png" alt="tier logo" className="logo-img" />
        </div>

        <nav className="menu">
        <Link href="/" className="linknav"> Inicio </Link>
        <Link href="/Inicial/sobre" className="linknav"> Sobre </Link>
        <Link href="/Inicial/contato" className="linknav"> Contato </Link>
        </nav>
        </header>
        {children}
        <footer className="footer">
            <p>© 2026 Nome da Empresa. Todos os direitos reservados.</p>
        </footer>
        </body>
    </html>
  );
}
