import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="header">

        <div className="logo">
        <img src="/imagens/tier11.png" alt="tier logo" className="logo-img" />
        </div>

        <nav className="menu">
        <Link href="/" className="linknav"> Inicio </Link>
        <Link href="Inicial/sobre" className="linknav"> Sobre </Link>
        <Link href="Inicial/contato" className="linknav"> Contato </Link>
        </nav>
        </header>

        {/* <footer className="footer">
        <div className="footer-container">
          <div className="footer-logo">
            <img src="/imagens/tier11.png" alt="tier logo" className="logo-img" />
            <h1>Tier 11</h1>
            <p>Unlock Your Business Potential With Facebook & Instagram Advertising</p>
          </div>
          </div>
          </footer> */}
        {children}
        </body>
    </html>
  );
}
